### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [anlsh/picl#1]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 396ff847c7161915fd39c5cd84389b337fdf0e83

*picl/tests* fails to build with the following error:

```
Unhandled NAME-CONFLICT in thread #<SB-THREAD:THREAD "main thread" RUNNING {10008D8083}>: USE-PACKAGE #<PACKAGE "PICL"> causes name-conflicts in #<PACKAGE "PICL/TESTS"> between the following symbols: PICL:APPLY, COMMON-LISP:APPLY

```

[Full log here](http://report.quicklisp.org/2020-12-19/failure-report/picl.html)

**Comment by anlsh** [comment]
Uh oh :/ I recently defined `picl:apply`, guess I did it wrong. I'll look into it

**Comment by anlsh** [comment]
Should be resolved now https://github.com/anlsh/picl/commit/a031d79b4b566e96a35e994f5d4885d245dfd93a
